In [42]:
import numpy as np
import pandas as pd
import datetime as dt
from matplotlib import pyplot as plt
4

In [8]:
n = np.arange(24).reshape(2,-1,2,2)
n.shape

(2, 3, 2, 2)

In [15]:
asDt = dt.datetime(2018,10,1,20,3,50)
aStr = dt.Strftime("%Y/%m%d")
print(aStr)

AttributeError: module 'datetime' has no attribute 'Strftime'

In [36]:
a = pd.Series([1,2,3])
a.index

RangeIndex(start=0, stop=3, step=1)

In [17]:

ser =pd.Series(np.arange(1,6),index=["a","b","c","d","e"])
s1 = ser.drop("a")
print(s1.values)
print(ser.values)

[2 3 4 5]
[1 2 3 4 5]


In [19]:
import pandas as pd
aList =[3,4,6,7,8]
ser=pd.Series(aList)
ser[2] =50
print(ser[2])
print(aList)

50
[3, 4, 6, 7, 8]


In [20]:
strFormat ="姓名:%s\t年龄:%d岁\t性别:%s"
print(strFormat%("保罗",29,"男"))

姓名:保罗	年龄:29岁	性别:男


In [21]:
aStr="hello world"
aList =list(aStr[0:7])
print(aList)

['h', 'e', 'l', 'l', 'o', ' ', 'w']


In [23]:
a= np.array([[1,2,3,4],[4,5,6,7]])
print(a.shape)

(2, 4)


In [24]:
aList =[1,5,3,9]
aList.sort()
print(aList)

[1, 3, 5, 9]


In [26]:
aTuple =(1,2)
bTuple=(4,5)
cTuple=aTuple +bTuple
print(cTuple)

(1, 2, 4, 5)


In [27]:
import numpy as np
aArray =np.arange(1,6)
bArray=aArray[-3:]
print(bArray)

[3 4 5]


In [29]:
A=[1,2,3,4]
B=A
A[1:3]=(8,9)
print("修改列表A的第2、3个元素的值")
print(B)

修改列表A的第2、3个元素的值
[1, 8, 9, 4]


In [30]:
import numpy as np
aArray =np.arange(1,6)
x=aArray[2]
print(x)

3


In [32]:
aStr ="Hello Worla"
aNum =11
if aStr is not aNum:
    print("astr和aNum不指向同一个对象")
else:
    print("astr和aNum不指向同一个对象。")

astr和aNum不指向同一个对象


In [39]:
A = np.arange(16)
print(A.min())
print(A.max())

0
15


In [40]:
print(pd.__version__)

1.4.2
