In [4]:
import numpy as np
print(np.__version__)
from matplotlib import pylab as plt
print(plt.__version__)

1.21.5
1.21.5


In [24]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
# print(type(b))
# print(b.shape)  # 打印形状
# print(b[:][:])
# print(b[0:][:-1])
# print(b[1,:])
print(b[:,np.newaxis,1])  # 获取列的原本形状

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2]
 [ 6]
 [10]]


In [30]:
c = np.array([[1,2,3,4,5,6],[3,4,5,6,7,8]])
print(c)
print(c.shape)
print(c[1][0])

[[1 2 3 4 5 6]
 [3 4 5 6 7 8]]
(2, 6)
3


In [4]:
# 方差
b = np.array([1,2,3,4])
print('方差', np.var(b))
print('标准差', np.std(b))

方差 1.25
标准差 1.118033988749895


In [7]:
# 加权平均值
c = np.array([20,30,50])
# 加权平均值
print("加权平均值", np.average(c))

加权平均值 33.333333333333336


In [14]:
ming = np.array([80,90,95])
gang = np.array([95,90,80])
ming_av = np.average(ming, weights=[0.2,0.3,0.5])
gang_av = np.average(gang, weights=[0.2,0.3,0.5])
print("小明的加权平均值",ming_av)
print("小刚的加权平均值",gang_av)
if ming_av > gang_av:
    print("小明综合成绩好")
else:
    print("小刚综合成绩好")

小明的加权平均值 90.5
小刚的加权平均值 86.0
小明综合成绩好


In [16]:
a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(a)
print(b)
print("数组点积", np.dot(a,b))

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[37 40]
 [85 92]]


In [17]:
# 向量点积

a = np.array([[1,2],[3,4]])
b = np.array([[11,12],[13,14]])
print(a)
print(b)
# 1乘以11加2乘以12加3乘以13加4乘以14。
print("向量的点积", np.vdot(a,b))



[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
向量的点积 130


In [19]:
# 向量内积
a = np.array([1, 2, 3])
b = np.array([0, 1, 0])
print("向量内积",np.inner(a,b))

c = np.array([[1,2],[3,4]])
d = np.array([[11,12],[13,14]])
print("向量内积",np.inner(c,d))
"""
1乘以11 2乘以12。1乘以13 2乘以14。
3乘以11 4乘以12。4乘以13 4乘以14。
"""

向量内积 2
向量内积 [[35 41]
 [81 95]]


In [20]:
# 矩阵乘积
a = np.array([[1, 0],[0, 1]])
b = np.array([[4, 1],[2,2]])
print(np.matmul(a,b))

[[4 1]
 [2 2]]


In [1]:
import os 
print(os.path.abspath('.'))

C:\Users\18354\Match
