In [1]:
import numpy as np


In [5]:
a = np.arange(12).reshape(3, 4)
print(a)
print("==============")
print(np.delete(a, 5))
print("==============")
print(np.delete(a, 1, axis=1))
print("==============")
print(np.delete(a, 1, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


In [7]:
a = np.arange(6).reshape(2,3)
print(a)
print(a[a>2])  # 大于2的元素
# 返回非0的数组元组的索引，其中a是要索引数组的条件
b = np.argwhere(a>2)  # 大于2的数的索引
print('*****************')
print(b)


[[0 1 2]
 [3 4 5]]
[3 4 5]
*****************
[[1 0]
 [1 1]
 [1 2]]
